[prod_servers]
sshapp1

[all:vars]
ansible_python_interpreter=/usr/bin/python3
# Karena kamu login sebagai fikri16, kita butuh izin sudo untuk perintah Docker
ansible_become=yes
ansible_become_method=sudo