events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Rute untuk Backend (NestJS)
        location /api/ {
            # Hapus akhiran /api/ agar Nginx meneruskan URI persis seperti aslinya
            proxy_pass http://api:3000;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # 🚨 WAJIB ADA untuk Google OAuth & Cloudflare Tunnel
            proxy_set_header X-Forwarded-Proto $scheme; 
        }

        # Rute untuk WebSocket(socket.io)
        location /api/socket.io/ {
            proxy_pass http://api:3000;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Rute untuk Frontend (Next.js)
        # Selain /api/, semua halaman masuk ke Next.js
        location / {
            proxy_pass http://web:3000;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # 🚨 WAJIB ADA untuk HTTPS Next.js & Server Actions
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Konfigurasi khusus agar WebSocket (HMR lokal / Next.js Image Optimization) tetap jalan
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}