events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Rute untuk Backend Golang (API)
        # Jika URL mengandung /api/, belokkan ke container Golang
        location /api/ {
            proxy_pass http://api:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Rute untuk Frontend SvelteKit (Web)
        # Selain /api/, semua halaman masuk ke SvelteKit
        location / {
            proxy_pass http://web:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Konfigurasi khusus agar HMR/Websocket Vite tetap jalan
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}